function [a]=jacobian32(b)
b=b*pi/180;
t1p=b(1);
t2p=b(2);
t3p=b(3);
t4p=b(4);
t5p=b(5);
t1v=b(6);
t2v=b(7);
t3v=b(8);
t4v=b(9);
t5v=b(10);
a=[17.05*sin(t1p)*t1v + 123.75*cos(t1p)*sin(t2p)*t1v + 123.75*cos(t2p)*sin(t1p)*t2v - 5.1*cos(t1p)*cos(t2p)*sin(t3p)*t1v - 5.1*cos(t1p)*cos(t3p)*sin(t2p)*t1v - 5.1*cos(t2p)*cos(t3p)*sin(t1p)*t2v - 5.1*cos(t2p)*cos(t3p)*sin(t1p)*t3v + 5.1*sin(t1p)*sin(t2p)*sin(t3p)*t2v + 5.1*sin(t1p)*sin(t2p)*sin(t3p)*t3v,       sin(t1p)*t1v*(123.75*cos(t2p) - 5.1*cos(t2p + t3p)) - 1.0*cos(t1p)*(5.1*sin(t2p + t3p)*t2v - 123.75*sin(t2p)*t2v + 5.1*sin(t2p + t3p)*t3v), - 5.1*sin(t1p)*cos(t2p + t3p)*t1v - 1.0*cos(t1p)*sin(t2p + t3p)*(5.1*t2v + 5.1*t3v);
123.75*sin(t1p)*sin(t2p)*t1v - 123.75*cos(t1p)*cos(t2p)*t2v - 17.05*cos(t1p)*t1v + 5.1*cos(t1p)*cos(t2p)*cos(t3p)*t2v + 5.1*cos(t1p)*cos(t2p)*cos(t3p)*t3v - 5.1*cos(t2p)*sin(t1p)*sin(t3p)*t1v - 5.1*cos(t3p)*sin(t1p)*sin(t2p)*t1v - 5.1*cos(t1p)*sin(t2p)*sin(t3p)*t2v - 5.1*cos(t1p)*sin(t2p)*sin(t3p)*t3v, - 1.0*sin(t1p)*(5.1*sin(t2p + t3p)*t2v - 123.75*sin(t2p)*t2v + 5.1*sin(t2p + t3p)*t3v) - 1.0*cos(t1p)*t1v*(123.75*cos(t2p) - 5.1*cos(t2p + t3p)),   5.1*cos(t1p)*cos(t2p + t3p)*t1v - 1.0*sin(t1p)*sin(t2p + t3p)*(5.1*t2v + 5.1*t3v);
                                                                                                                                                                                                                                                                                                                                                                                                                                                             0,                                                                                                 5.1*cos(t2p + t3p)*t2v - 123.75*cos(t2p)*t2v + 5.1*cos(t2p + t3p)*t3v,                                                                         5.1*cos(t2p + t3p)*(t2v + t3v);
                                                                                                                                                                                                                                                                                                                                                                                                                                                              0,                                                                                                                                                                                        cos(t1p)*t1v,                                                                                                        cos(t1p)*t1v;
                                                                                                                                                                                                                                                                                                                                                                                                                                                              0,                                                                                                                                                                                        sin(t1p)*t1v,                                                                                                        sin(t1p)*t1v;
                                                                                                                                                                                                                                                                                                                                                                                                                                                              0,                                                                                                                                                                                                                0,                                                                                                                                0];

end